import { describe, expect, it } from 'vitest'
import fs from 'node:fs'
import path from 'node:path'

describe('App source', () => {
  it('renders fixed desktop shell with theme switch, notice layer and retained drafts after submit', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')
    const preloadSource = fs.readFileSync(path.resolve(process.cwd(), 'main/preload.js'), 'utf8')

    expect(source).toContain('AppTopBar')
    expect(source).toContain('ActivationGate')
    expect(source).toContain('WorkspaceSidebar')
    expect(source).toContain('DesignWorkspace')
    expect(source).toContain('TaskManagerSidebar')
    expect(source).toContain('FloatingAgentLauncher')
    expect(source).toContain('FloatingAgentPanel')
    expect(source).toContain('shell-grid')
    expect(source).toContain('秋 Ai')
    expect(source).toContain('暗黑')
    expect(source).not.toContain('明亮')
    expect(source).not.toContain('护眼')
    expect(source).toContain('getStudioSnapshot')
    expect(source).toContain('getActivationStatus')
    expect(source).toContain('importLicenseFile')
    expect(source).toContain('saveSettings')
    expect(source).toContain('showActionFeedback')
    expect(source).toContain('buildErrorMessage')
    expect(source).toContain('buildTaskFailureFeedbackMessage')
    expect(source).toContain('app-notice-layer')
    expect(source).toContain('成功')
    expect(source).toContain('失败')
    expect(source).toContain('openClearRuntimeConfirm')
    expect(source).toContain('confirmClearRuntimeState')
    expect(source).toContain('@cleanup-click="openClearRuntimeConfirm"')
    expect(source).toContain('isClearRuntimeConfirmVisible')
    expect(source).toContain('scheduleDraftPersist')
    expect(source).toContain('hasActiveStudioTasks')
    expect(source).toContain('activationState')
    expect(source).toContain('isActivated')
    expect(source).toContain('handleImportLicense')
    expect(source).toContain('handleCopyDeviceCode')
    expect(source).toContain('replaceDraft')
    expect(source).not.toContain('await resetActiveDraftAfterSubmit()')
    expect(source).toContain('可能导致保留原图或生成失败')
    expect(source).toContain('AdminPasswordDialog')
    expect(source).toContain('AdminApiKeyDialog')
    expect(source).toContain('adminLogoClickCount')
    expect(source).toContain('isAdminPasswordDialogVisible')
    expect(source).toContain('isAdminApiConfigUnlocked')
    expect(source).toContain('isAdminApiKeyDialogVisible')
    expect(source).toContain('adminPasswordDraft')
    expect(source).toContain('adminApiKeyDraft')
    expect(source).toContain('handleConfirmAdminPassword')
    expect(source).toContain('saveAdminApiKey')
    expect(source).toContain('askAgentAssistant')
    expect(source).toContain('isAgentPanelOpen')
    expect(source).toContain('currentAgentConversationSession')
    expect(source).toContain('handleToggleAgentPanel')
    expect(source).toContain('handleSendAgentMessage')
    expect(source).toContain('handleConfirmAgentFill')
    expect(source).toContain('getAgentScenePresetsByMenu')
    expect(source).toContain('currentAgentScenePresets')
    expect(source).toContain('handleSelectAgentScenePreset')
    expect(source).toContain("currentAgentUserGoal.value = preset.promptText")
    expect(source).toContain('replaceDraft(activeMenu.value, nextDraft)')
    expect(source).toContain('@confirm-fill="handleConfirmAgentFill"')
    expect(source).toContain(':active-menu="activeMenu"')
    expect(source).toContain(':scene-presets="currentAgentScenePresets"')
    expect(source).toContain('@select-scene-preset="handleSelectAgentScenePreset"')
    expect(source).toContain(':conversation-messages="currentAgentMessages"')
    expect(source).toContain(':pending-question="currentAgentPendingQuestion"')
    expect(source).toContain(':confirm-card="currentAgentConfirmCard"')
    expect(source).toContain('@send="handleSendAgentMessage"')
    expect(source).not.toContain("handleSelectAgentScenePreset(preset) { await handleSendAgentMessage(")
    expect(source).toContain('resolveAgentPromptTemplateById')
    expect(source).toContain('applyAgentSuggestionToSeriesGenerate')
    expect(source).toContain('applyAgentSuggestionToSeriesDesign')
    expect(source).toContain('nextDraft.promptAssignments = nextDraft.promptAssignments.map((assignment) => ({')
    expect(source).toContain('nextDraft.imageAssignments = nextDraft.imageAssignments.map((assignment) => ({')
    expect(source).toContain('negativePrompt: matchedTemplate?.prompt || \'\'')
    expect(source).toContain('templateId: suggestion.imageTypeTemplateId || assignment.templateId || DEFAULT_EMPTY_PROMPT_TEMPLATE_ID')
    expect(source).toContain('prompt: suggestion.exclusivePrompt')
    expect(source).toContain('globalPrompt = suggestion.globalStylePrompt')
    expect(source).toContain('activeMenu.value !== suggestion.menuKey')
    expect(source).toContain('AI智能体已填写当前页面参数，请确认后手动提交任务')
    expect(source).toContain('listNegativePromptTemplates')
    expect(source).toContain('saveNegativePromptTemplate')
    expect(source).toContain('removeNegativePromptTemplate')
    expect(source).toContain('negativePromptTemplates')
    expect(source).toContain('fixedNegativePromptTemplates')
    expect(source).toContain('customNegativePromptTemplates')
    expect(source).toContain('loadNegativePromptTemplateState')
    expect(source).toContain('applyNegativeTemplateSelection')
    expect(source).toContain("field === 'negativeTemplateId'")
    expect(source).toContain("negativePrompt: matchedTemplate?.prompt || ''")
    expect(source).toContain('管理员验证失败：密码错误')
    expect(source).toContain("message: '管理员验证通过，请继续保存 API-Key'")
    expect(source).toContain("message: 'API-Key 已保存成功'")
    expect(source).toContain('isAdminApiConfigUnlocked.value = false')
    expect(source).toContain('adminApiKeyDraft.value = settings.apiKey || \'\'')
    expect(source).toContain('if (adminLogoClickCount.value >= 5)')
    expect(source).not.toContain('@wechat-click=')
    expect(source).not.toContain('handleWechatClick')
    expect(preloadSource).not.toContain('PROMPT_TAGS_LIST')
    expect(preloadSource).not.toContain('PROMPT_TAGS_SAVE_CATEGORY')
    expect(preloadSource).not.toContain('PROMPT_TAGS_SAVE_TAG')
    expect(preloadSource).not.toContain('PROMPT_TAGS_REMOVE_TAG')
    expect(preloadSource).not.toContain('PROMPT_TAGS_REMOVE_CATEGORY')
  })

  it('uses prompt library sidebar item together with studio menus without copywriting', () => {
    const sidebarSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/WorkspaceSidebar.vue'), 'utf8')
    const appSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')

    expect(sidebarSource).toContain('工作台')
    expect(sidebarSource).toContain('单图测试')
    expect(sidebarSource).toContain('单图设计')
    expect(sidebarSource).toContain('套图设计')
    expect(sidebarSource).toContain('套图生成')
    expect(sidebarSource).toContain('模型价格')
    expect(sidebarSource).toContain('提示词库')
    expect(sidebarSource).toContain('Agent设置')
    expect(sidebarSource).not.toContain('文案设计')
    expect(sidebarSource).toContain("key: 'workspace'")
    expect(sidebarSource).toContain("key: 'single-image'")
    expect(sidebarSource).toContain("key: 'single-design'")
    expect(sidebarSource).toContain("key: 'series-design'")
    expect(sidebarSource).toContain("key: 'series-generate'")
    expect(sidebarSource).toContain("key: 'model-pricing'")
    expect(sidebarSource).toContain("key: 'prompt-library'")
    expect(sidebarSource).toContain("key: 'agent-settings'")
    expect(sidebarSource).not.toContain("key: 'copywriting'")
    expect(appSource).not.toContain("{ key: 'copywriting', label: '文案设计' }")
    expect(appSource).toContain("{ key: 'prompt-library', label: '提示词库' }")
    expect(appSource).toContain("{ key: 'agent-settings', label: 'Agent设置' }")
    expect(appSource.indexOf("{ key: 'prompt-library', label: '提示词库' }")).toBeLessThan(
      appSource.indexOf("{ key: 'agent-settings', label: 'Agent设置' }")
    )
    expect(sidebarSource).toContain('菜单点击事件预留')
  })

  it('renders task sidebar with workspace queue and design export modes only', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/TaskManagerSidebar.vue'), 'utf8')

    expect(source).toContain('任务队列')
    expect(source).toContain('单图测试')
    expect(source).toContain('单图设计')
    expect(source).toContain('套图设计')
    expect(source).toContain('套图生成')
    expect(source).not.toContain('文案设计')
    expect(source).toContain('等待中')
    expect(source).toContain('进行中')
    expect(source).toContain('待确认')
    expect(source).toContain('已完成')
    expect(source).toContain('失败')
    expect(source).toContain('生成时间')
    expect(source).toContain('formatTaskNumber')
    expect(source).toContain('10 个任务')
    expect(source).toContain('pagination-arrow-button')
    expect(source).toContain('pagination-arrow-button__triangle--left')
    expect(source).toContain('pagination-arrow-button__triangle--right')
    expect(source).toContain('aria-label="上一页"')
    expect(source).toContain('aria-label="下一页"')
    expect(source).toContain('currentPage')
    expect(source).toContain('结束任务')
    expect(source).toContain('stop-task')
    expect(source).toContain('isStoppableTask')
    expect(source).toContain('ResultExportPanel')
    expect(source).toContain('showWorkspaceTasks')
    expect(source).toContain('showExportPanel')
    expect(source).toContain('downloadCleanupEnabled')
    expect(source).toContain('toggle-download-cleanup')
    expect(source).not.toContain("props.activeMenu === 'prompt-library'")
    expect(source).not.toContain("props.activeMenu === 'copywriting'")
    expect(source).toContain('当前页面暂无侧边内容')
  })

  it('renders dashboard workspace, prompt library, single-block model pricing, and focus display design pages', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/DesignWorkspace.vue'), 'utf8')

    expect(source).toContain('WorkspaceDashboard')
    expect(source).toContain("activeMenu === 'workspace'")
    expect(source).toContain('PromptLibraryPanel')
    expect(source).toContain("activeMenu === 'prompt-library'")
    expect(source).toContain('AgentSettingsPanel')
    expect(source).toContain("activeMenu === 'agent-settings'")
    expect(source).toContain('ParameterSettingsPanel')
    expect(source).toContain('ResultDisplayPanel')
    expect(source).not.toContain('ResultExportPanel')
    expect(source).toContain("activeMenu === 'model-pricing'")
    expect(source).toContain('workspace-panels--single')
    expect(source).toContain('workspace-panels--focus-display')
    expect(source).toContain('single-design')
    expect(source).toContain('latestTask')
    expect(source).toContain(':prompt-templates="allPromptTemplates"')
    expect(source).toContain(':custom-prompt-templates="customPromptTemplates"')
    expect(source).toContain(':fixed-negative-prompt-templates="fixedNegativePromptTemplates"')
    expect(source).toContain(':custom-negative-prompt-templates="customNegativePromptTemplates"')
    expect(source).not.toContain('@update-api-key=')
    expect(source).not.toContain('@switch-api-key=')
    expect(source).not.toContain('@save-api-config=')
    expect(source).not.toContain('select-copywriting-images')
    expect(source).not.toContain('clear-copywriting-images')
  })

  it('docks the agent launcher in the right-side reserved slot instead of the overlapping fixed corner trigger', () => {
    const appSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')

    expect(appSource).toContain('shell-grid__tasks-stack')
    expect(appSource).toContain('shell-grid__agent-slot')
    expect(appSource.indexOf('FloatingAgentLauncher')).toBeLessThan(appSource.indexOf('TaskManagerSidebar'))
  })

  it('defines image-generation model pools and omits copywriting-specific options', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')

    expect(source).not.toContain('const copywritingModelOptions = [')
    expect(source).toContain('const imageModelOptions = [')
    expect(source).toContain('nano-banana-fast')
    expect(source).toContain('nano-banana-pro-4k-vip')
    expect(source).toContain('const currentModelOptions = computed(() => {')
    expect(source).not.toContain("if (activeMenu.value === 'copywriting')")
    expect(source).toContain('currentModelOptions')
    expect(source).toContain('const allPromptTemplates = computed(() => {')
    expect(source).toContain('Math.min(500')
    expect(source).toContain('currentLongRunningHint')
    expect(source).toContain('currentTaskScaleSummary')
    expect(source).toContain('normalizeBatchPrompts')
    expect(source).toContain("templateId: currentAssignment.templateId || DEFAULT_EMPTY_PROMPT_TEMPLATE_ID")
    expect(source).toContain('differentialEnabled')
    expect(source).toContain('batchPrompts')
    expect(source).toContain('resolveTaskScaleSummary')
    expect(source).toContain("if (currentTaskScaleSummary.value?.level === 'block')")
    expect(source).toContain('当前任务量很大，将进入长队列执行。')
    expect(source).toContain('当前任务量较大，生成时间会明显变长。')
    expect(source).toContain("const DEFAULT_EMPTY_PROMPT_TEMPLATE_ID = 'system-empty-image-type'")
    expect(source).toContain("const DEFAULT_EMPTY_NEGATIVE_TEMPLATE_ID = 'system-empty-negative-prompt'")
    expect(source).toContain("const DEFAULT_EMPTY_PROMPT_TEMPLATE_NAME = '无类型图片'")
    expect(source).toContain("prompt: ''")
    expect(source).toContain("negativeTemplateId: DEFAULT_EMPTY_NEGATIVE_TEMPLATE_ID")
    expect(source).toContain("templateId: currentAssignment.templateId || DEFAULT_EMPTY_PROMPT_TEMPLATE_ID")
    expect(source).toContain("templateId: DEFAULT_EMPTY_PROMPT_TEMPLATE_ID")
    expect(source).toContain("imageType: currentAssignment.imageType || ''")
    expect(source).toContain("imageType: assignment.imageType || ''")
    expect(source).toContain("imageType: ''")
    expect(source).toContain("return promptTemplates.value.filter((item) => item.source === 'system-fixed')")
    expect(source).toContain("return negativePromptTemplates.value.filter((item) => item.source === 'system-fixed')")
    expect(source).not.toContain('filterInvalidSelectedGlobalTagIds')
    expect(source).not.toContain('cleanupDraftSelectedGlobalTags')
    expect(source).toContain('await persistDraftPatch(menuKey, nextDraft)')
  })

  it('defines a recharge catalog for the model pricing page', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')

    expect(source).toContain('const rechargePricingCatalog = [')
    expect(source).toContain("price: '30¥'")
    expect(source).toContain("credits: '100000积分'")
    expect(source).toContain("validity: '一周'")
    expect(source).toContain("bonus: '送25%'")
    expect(source).toContain("validity: '一月'")
    expect(source).toContain("validity: '一季'")
    expect(source).toContain("validity: '半年'")
    expect(source).toContain("validity: '一年'")
    expect(source).toContain("price: '3000¥'")
    expect(source).toContain("credits: '20000000积分'")
    expect(source).toContain("validity: '三年'")
    expect(source).toContain(':recharge-pricing-catalog="rechargePricingCatalog"')
  })

  it('keeps only needed pricing models and orders them by ascending credits', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')

    expect(source).not.toContain("name: 'gemini-3-pro'")
    expect(source).not.toContain("name: 'gemini-3.1-pro'")
    expect(source).not.toContain("name: 'gemini-2.5-pro'")
    expect(source).not.toContain("name: 'sora-create-character'")
    expect(source).not.toContain("name: 'sora-upload-character'")

    expect(source.indexOf("name: 'nano-banana-fast'")).toBeLessThan(source.indexOf("name: 'gpt-image-2'"))
    expect(source.indexOf("name: 'gpt-image-2'")).toBeLessThan(source.indexOf("name: 'nano-banana-2'"))
    expect(source.indexOf("name: 'nano-banana-2'")).toBeLessThan(source.indexOf("name: 'nano-banana'"))
    expect(source.indexOf("name: 'nano-banana'")).toBeLessThan(source.indexOf("name: 'nano-banana-2-cl'"))
    expect(source.indexOf("name: 'nano-banana-2-cl'")).toBeLessThan(source.indexOf("name: 'nano-banana-pro'"))
  })

  it('wires image upload actions through the workspace shell', () => {
    const appSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')
    const workspaceSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/DesignWorkspace.vue'), 'utf8')

    expect(appSource).toContain('pickStudioInputAssets')
    expect(appSource).toContain('uploadDirectoryDrafts')
    expect(appSource).toContain('handleUploadDirectoryDraftUpdate')
    expect(appSource).toContain('handleSaveUploadDirectory')
    expect(appSource).toContain('handleOpenSingleImagePicker')
    expect(appSource).toContain('handleOpenSingleImagePicker')
    expect(workspaceSource).toContain('select-single-design-image')
    expect(appSource).toContain('handleOpenSingleDesignImagePicker')
    expect(appSource).toContain('handleOpenSeriesDesignPicker')
    expect(appSource).toContain('handleOpenSeriesGeneratePicker')
    expect(appSource).toContain('saveSettings({')
    expect(appSource).toContain('uploadDirectories:')
    expect(appSource).toContain("preview: preview")
    expect(appSource).toContain("typeof file.preview === 'string' ? file.preview : ''")
    expect(appSource).not.toContain('globalUploadDirectory')
    expect(workspaceSource).toContain('save-upload-directory')
    expect(workspaceSource).toContain('update-upload-directory-draft')
    expect(appSource).not.toContain('handleSelectCopywritingImages')
    expect(appSource).not.toContain('handleClearCopywritingImages')
    expect(workspaceSource).not.toContain('select-copywriting-images')
    expect(workspaceSource).not.toContain('clear-copywriting-images')
    expect(appSource).not.toContain('copyMode')
    expect(appSource).not.toContain('referenceImages')
    expect(appSource).not.toContain('copywritingImageInput')
    expect(appSource).not.toContain('return encodeURI(`file:///')
  })

  it('wires export panel output-directory action through the desktop bridge', () => {
    const appSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')
    const taskSidebarSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/TaskManagerSidebar.vue'), 'utf8')

    expect(taskSidebarSource).toContain('open-output-directory')
    expect(taskSidebarSource).toContain('exportItems')
    expect(taskSidebarSource).toContain('selectedExportIds')
    expect(taskSidebarSource).toContain('stop-task')
    expect(appSource).toContain('handleOpenOutputDirectory')
    expect(appSource).toContain('handleStopTask')
    expect(appSource).toContain('stopStudioTask')
    expect(appSource).toContain('openOutputDirectory')
    expect(appSource).toContain('latestTaskForActiveMenu')
  })

  it('only shows latest task progress for the active menu instead of falling back to other modules', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')

    expect(source).toContain('const matchedTask = sortedTasks.value.find((task) => task.menuKey === activeMenu.value)')
    expect(source).toContain('return matchedTask || null')
    expect(source).not.toContain('return matchedTask || sortedTasks.value[0] || null')
  })

  it('optimistically updates queued task state after submit instead of waiting on a full snapshot refresh', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')

    expect(source).toContain('function upsertTaskIntoState(task)')
    expect(source).toContain('const createdTask = await createStudioTask({')
    expect(source).toContain('upsertTaskIntoState(createdTask)')
    expect(source).not.toContain('await resetActiveDraftAfterSubmit()')
    expect(source).not.toContain("window.confirm('确认执行一键清理吗？")
    expect(source).toContain('buildDraftForSubmit')
    expect(source).toContain("globalPrompt: String(draft.globalPrompt || '')")
    expect(source).not.toContain('buildGlobalPromptFromSelectedTags')
    expect(source).not.toContain('selectedGlobalTagIds')
    expect(source).toContain('detectPromptRisk')
    expect(source).toContain('void refreshStudioRuntimeState()')
    expect(source).toContain('handleFailedTaskNotifications')
    expect(source).toContain('previousTaskStatusMap')
    expect(source).toContain('图片内容触发平台审核限制')
    expect(source).toContain('图片生成长时间没有进展')
    expect(source).toContain('服务配置无效')
    expect(source).toContain('handleRefreshDashboardTotalCredits')
    expect(source).toContain('handleRefreshDashboardRemainingCredits')
    expect(source).toContain('refreshDashboardCredits')
    expect(source).toContain("target: 'total'")
    expect(source).toContain("target: 'remaining'")
    expect(source).not.toContain('handleSaveApiConfig')
    expect(source).not.toContain('handleApiKeyUpdate')
    expect(source).not.toContain('handleSwitchApiKey')
  })

  it('persists the export auto-cleanup preference and deletes selected folders after successful download', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')

    expect(source).toContain('downloadCleanupEnabled')
    expect(source).toContain('handleToggleDownloadCleanup')
    expect(source).toContain('downloadCleanupEnabled: value')
    expect(source).toContain('const exportedIds = [...selectedExportIds.value]')
    expect(source).toContain('if (downloadCleanupEnabled.value)')
    expect(source).toContain('批量下载成功，源结果文件夹已自动删除')
    expect(source).toContain('批量下载成功，请确认压缩包完整后再手动清理源结果文件夹')
    expect(source).toContain('Promise.allSettled(exportedIds.map((exportItemId) => deleteStudioExportItem({')
    expect(source).toContain('批量下载成功，但部分结果文件夹自动清理失败')
  })

  it('preserves export folder checkbox choices across refreshes while auto-selecting only new items', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')

    expect(source).toContain('const selectedExportIdsByMenu = ref(createEmptyExportSelectionsByMenu())')
    expect(source).toContain('function createEmptyExportSelectionsByMenu()')
    expect(source).toContain('function syncSelectedExportIdsForMenu(menuKey)')
    expect(source).toContain('const previousSelection = new Set(selectedExportIdsByMenu.value[menuKey] || [])')
    expect(source).toContain('const existingIds = new Set(previousItems.map((item) => item?.id).filter((itemId) => typeof itemId === \'string\' && itemId.trim()))')
    expect(source).toContain('.filter((itemId) => !existingIds.has(itemId) || previousSelection.has(itemId))')
    expect(source).toContain('selectedExportIdsByMenu.value = {')
    expect(source).toContain('[menuKey]: nextSelectedIds')
    expect(source).not.toContain('selectedExportIds.value = resolveSelectedExportIdsForMenu(activeMenu.value)')
    expect(source).not.toContain('selectedExportIds.value = resolveSelectedExportIdsForMenu(menuKey)')
  })

  it('bumps a reset key after one-key cleanup so parameter inputs remount against the cleared drafts', () => {
    const appSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')
    const workspaceSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/DesignWorkspace.vue'), 'utf8')

    expect(appSource).toContain('const runtimeResetSequence = ref(0)')
    expect(appSource).toContain('runtimeResetSequence.value += 1')
    expect(appSource).toContain(':runtime-reset-sequence="runtimeResetSequence"')
    expect(workspaceSource).toContain(":key=\"`${activeMenu}-${runtimeResetSequence}`\"")
  })

  it('uses an in-app confirmation dialog for one-key cleanup instead of blocking window.confirm', () => {
    const appSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')

    expect(appSource).toContain('isClearRuntimeConfirmVisible.value = true')
    expect(appSource).toContain('isClearRuntimeConfirmVisible.value = false')
    expect(appSource).toContain(':is-clear-runtime-confirm-visible="isClearRuntimeConfirmVisible"')
    expect(appSource).toContain('@confirm-clear-runtime-state="confirmClearRuntimeState"')
    expect(appSource).not.toContain("window.confirm('确认执行一键清理吗？将重置参数设置、效果展示与日志缓存")
  })

  it('stores chat-first AI conversation sessions per menu with isolated reset helpers', () => {
    const appSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')
    const storeSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/stores/agentConversationStore.js'), 'utf8')

    expect(storeSource).toContain('createDefaultAgentConversationSession')
    expect(storeSource).toContain('createAgentConversationStore')
    expect(storeSource).toContain('sessionsByMenu')
    expect(storeSource).toContain('resolveAgentConversationSession(store, menuKey)')
    expect(storeSource).toContain('clearAgentConversationSession(store, menuKey)')
    expect(storeSource).toContain("status: 'idle'")
    expect(storeSource).toContain('messages: []')
    expect(storeSource).toContain('draftSuggestion: null')
    expect(storeSource).toContain('pendingQuestion: null')
    expect(storeSource).toContain('confirmCard: null')
    expect(storeSource).toContain('lastApplyResult: null')
    expect(storeSource).not.toContain("userGoal: ''")
    expect(storeSource).not.toContain('suggestion: null')
    expect(storeSource).not.toContain('isLoading: false')

    expect(appSource).toContain("from './stores/agentConversationStore'")
    expect(appSource).toContain('reactive(createAgentConversationStore())')
    expect(appSource).toContain('resolveAgentConversationSession(agentConversationStore, activeMenu.value)')
    expect(appSource).toContain('clearAgentConversationSession(agentConversationStore, activeMenu.value)')
    expect(appSource).toContain('const currentAgentConversationSession = computed(() =>')
    expect(appSource).toContain('return resolveAgentConversationSession(agentConversationStore, activeMenu.value)')
    expect(appSource).not.toContain('resolveAgentConversationSession(activeMenu.value)')
    expect(appSource).not.toContain('clearAgentConversationSession(activeMenu.value)')
    expect(appSource).not.toContain("currentAgentConversationSession.value.userGoal = preset.promptText")
    expect(appSource).not.toContain('currentAgentConversationSession.value.isLoading = true')
    expect(appSource).not.toContain('currentAgentConversationSession.value.suggestion = await generateAgentSuggestion({')
    expect(appSource).not.toContain('const suggestion = currentAgentConversationSession.value.suggestion')
    expect(appSource).not.toContain(':user-goal="currentAgentConversationSession.userGoal"')
    expect(appSource).not.toContain(':is-loading="currentAgentConversationSession.isLoading"')
    expect(appSource).not.toContain(':suggestion="currentAgentConversationSession.suggestion"')
    expect(appSource).not.toContain('@update:user-goal="currentAgentConversationSession.userGoal = $event"')
  })
})
