import { describe, expect, it } from 'vitest'
import fs from 'node:fs'
import path from 'node:path'
import { parse } from '@vue/compiler-sfc'

describe('component sources', () => {
  it('parses PromptLibraryPanel.vue without template syntax errors', () => {
    const promptLibrarySource = fs.readFileSync(
      path.resolve(process.cwd(), 'renderer/src/components/PromptLibraryPanel.vue'),
      'utf8'
    )

    expect(() => parse(promptLibrarySource)).not.toThrow()
  })

  it('contains top bar, parameter, effect and export panel placeholders without copywriting blocks', () => {
    const appSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')
    const activationSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/ActivationGate.vue'), 'utf8')
    const topbarSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/AppTopBar.vue'), 'utf8')
    const parameterSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/ParameterSettingsPanel.vue'), 'utf8')
    const styleSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/assets/styles.css'), 'utf8')
    const resultSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/ResultDisplayPanel.vue'), 'utf8')
    const exportSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/ResultExportPanel.vue'), 'utf8')
    const dashboardSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/WorkspaceDashboard.vue'), 'utf8')
    const promptLibrarySource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/PromptLibraryPanel.vue'), 'utf8')
    const adminPasswordDialogSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/AdminPasswordDialog.vue'), 'utf8')
    const adminApiKeyDialogSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/AdminApiKeyDialog.vue'), 'utf8')

    expect(activationSource).toContain('设备码')
    expect(activationSource).toContain('复制设备码')
    expect(activationSource).toContain('导入授权文件')
    expect(activationSource).toContain('刷新校验')
    expect(activationSource).toContain('activationState')
    expect(activationSource).toContain('已激活')

    expect(topbarSource).toContain('Logo 点击事件预留')
    expect(topbarSource).toContain('主题切换事件预留')
    expect(topbarSource).toContain('一键清理按钮点击事件预留')
    expect(topbarSource).toContain('微信 / 企业微信图片预览切换')
    expect(topbarSource).toContain('一键清理')
    expect(topbarSource).toContain('v-if="themeOptions.length > 1"')
    expect(topbarSource).toContain('weixin.png')
    expect(topbarSource).toContain('qiyeweixin.png')
    expect(topbarSource).not.toContain('Qiushui.jpg')
    expect(topbarSource).toContain('Dockerfans.jpg')
    expect(topbarSource).toContain('Qiyeweixin.jpg')
    expect(topbarSource).toContain('微信')
    expect(topbarSource).toContain('企业微信')
    expect(topbarSource).toContain('topbar-contact-button')
    expect(topbarSource).toContain('contact-preview-modal')
    expect(topbarSource).toContain('closeContactPreview')
    expect(topbarSource).toContain('activationSummary')
    expect(topbarSource).toContain('已激活')
    expect(topbarSource).toContain('topbar-right-actions')
    expect(topbarSource.indexOf('topbar-activation-pill')).toBeLessThan(topbarSource.indexOf('topbar-clean-button'))
    expect(topbarSource.indexOf('topbar-clean-button')).toBeLessThan(topbarSource.indexOf('topbar-contact-actions'))
    expect(topbarSource).toContain('brand-click')

    expect(parameterSource).toContain('提交任务事件预留')
    expect(parameterSource).toContain('scrollbar-hidden')
    expect(parameterSource).toContain('任务名称')
    expect(parameterSource).toContain('默认打开目录')
    expect(parameterSource).toContain('保存目录')
    expect(parameterSource).toContain('upload-directory-row')
    expect(parameterSource).toContain('upload-directory-input')
    expect(parameterSource).toContain('提示词输入区域')
    expect(parameterSource).toContain('模型选择')
    expect(parameterSource).toContain('shangchuan.png')
    expect(parameterSource).toContain('baocun.png')
    expect(parameterSource).toContain('moban.png')
    expect(parameterSource).toContain('对比模型 1')
    expect(parameterSource).toContain('对比模型 4')
    expect(parameterSource).toContain('设计模型')
    expect(appSource).toContain('A4 竖版')
    expect(appSource).toContain('A4 横版')
    expect(appSource).toContain('A5 竖版')
    expect(appSource).toContain('A5 横版')
    expect(appSource).toContain('8K 横版')
    expect(appSource).toContain('8K 竖版')
    expect(parameterSource).toContain('全局主提示词')
    expect(parameterSource).toContain('FormTextControl')
    expect(parameterSource).toContain('反向提示词')
    expect(parameterSource).toContain('请选择反向提示词模板')
    expect(parameterSource).toContain('图片专属提示词')
    expect(parameterSource).toContain('生成组数')
    expect(parameterSource).toContain('全局风格提示词')
    expect(parameterSource).toContain('生成数量')
    expect(parameterSource).toContain('批次')
    expect(parameterSource).toContain('逐张提示词配置')
    expect(parameterSource).toContain('第 ${index + 1} 张')
    expect(parameterSource).toContain('assignment-card__template-row')
    expect(parameterSource).toContain('assignment-card__top')
    expect(parameterSource).toContain('assignment-card__media')
    expect(parameterSource).toContain('assignment-card__media-frame')
    expect(parameterSource).toContain('assignment-card__media-copy')
    expect(styleSource).toContain('grid-template-columns: minmax(0, 1fr) minmax(0, 1fr)')
    expect(styleSource).toContain('min-height: 220px')
    expect(styleSource).toContain('aspect-ratio: 1 / 1')
    expect(styleSource).toContain('width: 100%')
    expect(styleSource).toContain('height: 100%')
    expect(styleSource).toContain('object-fit: contain')
    expect(parameterSource).toContain('assignment-card__control-panel')
    expect(parameterSource).toContain('assignment-card__control-stack')
    expect(parameterSource).toContain('assignment-card__compact-select')
    expect(parameterSource).toContain('差异化')
    expect(parameterSource).toContain('专属提示词${batchPromptIndex + 1}')
    expect(parameterSource).toContain('assignment.differentialEnabled === true')
    expect(parameterSource).toContain("updateAssignment(index, 'differentialEnabled', $event.target.checked)")
    expect(parameterSource).toContain("updateSeriesGenerateAssignment(index, 'differentialEnabled', $event.target.checked)")
    expect(parameterSource).toContain('updateAssignmentBatchPrompt')
    expect(parameterSource).toContain('updateSeriesGenerateBatchPrompt')
    expect(parameterSource).toContain('单张比例')
    expect(parameterSource).toContain('单张模型')
    expect(parameterSource).toContain('assignment-card__template-select')
    expect(parameterSource).toContain('assignment-card__prompt-field--flush')
    expect(parameterSource).toContain('rows="3"')
    expect(parameterSource).toContain('promptTemplateOptions')
    expect(parameterSource).toContain('select-icon-field')
    expect(parameterSource).toContain('select-icon-field__icon')
    expect(parameterSource).toContain('assignment.sizeLabel ||')
    expect(parameterSource).toContain('promptTemplateOptions')
    expect(parameterSource).toContain('negativePromptTemplateOptions')
    expect(parameterSource).toContain('templateId')
    expect(parameterSource).toContain('handleTemplateSelection')
    expect(parameterSource).toContain("emitField('negativeTemplateId'")
    expect(parameterSource).toContain('resolveTemplateById')
    expect(parameterSource).not.toContain('customPromptTemplates')
    expect(parameterSource).not.toContain('请选择图片类型')
    expect(parameterSource).not.toContain('请选择要补充的提示词模板')
    expect(parameterSource).not.toContain('补充到当前提示词')
    expect(parameterSource).not.toContain('daoru.png')
    expect(parameterSource).not.toContain('导入提示词模板')
    expect(parameterSource).not.toContain('openPromptImport')
    expect(parameterSource).not.toContain('appendPromptTemplate')
    expect(parameterSource).toContain('number-stepper')
    expect(parameterSource).toContain('stepper-button stepper-button--decrement')
    expect(parameterSource).toContain('stepper-button stepper-button--increment')
    expect(parameterSource).toContain('stepper-button__triangle--left')
    expect(parameterSource).toContain('stepper-button__triangle--right')
    expect(parameterSource).toContain("stepField('generateCount', draftForm.generateCount, -1, 1, 500)")
    expect(parameterSource).toContain("updateStepperField('generateCount', $event.target.value, 1, 500)")
    expect(parameterSource).toContain("stepField('batchCount', draftForm.batchCount, -1, 1, 9999)")
    expect(parameterSource).toContain("updateStepperField('batchCount', $event.target.value, 1, 9999)")
    expect(parameterSource).toContain('submitButtonState')
    expect(parameterSource).toContain('taskScaleSummary')
    expect(parameterSource).toContain('task-scale-summary')
    expect(parameterSource).toContain('当前任务预计输出')
    expect(parameterSource).toContain('风险等级')
    expect(parameterSource).toContain('预计积分')
    expect(parameterSource).toContain('提交成功√')
    expect(parameterSource).not.toContain("activeMenu === 'copywriting'")
    expect(parameterSource).not.toContain('select-copywriting-images')
    expect(parameterSource).not.toContain('clear-copywriting-images')
    expect(parameterSource).not.toContain('单独提示词')
    expect(parameterSource).not.toContain('文案类型')
    expect(parameterSource).not.toContain('批量输入方式')
    expect(parameterSource).not.toContain('批量内容')
    expect(parameterSource).not.toContain('逐行输入')
    expect(parameterSource).not.toContain('导入 TXT')
    expect(parameterSource).not.toContain('导入 CSV')
    expect(parameterSource).not.toContain("{{ menuLabel }} / {{ menuHint }}")
    expect(parameterSource).not.toContain('不上传图片则直接按文生图处理，上传后自动按图生图处理。')
    expect(parameterSource).not.toContain('固定模型，优先用于稳定快速对比')
    expect(parameterSource).not.toContain('固定模型，作为标准效果参考')
    expect(parameterSource).not.toContain('示例：选中 3 张图，生成组数为 3，则最终输出 3 组完整套图。')

    expect(resultSource).toContain("activeMenu === 'model-pricing'")
    expect(resultSource).toContain('积分充值')
    expect(resultSource).toContain('section-title section-title--centered')
    expect(resultSource).toContain('recharge-price-grid')
    expect(resultSource).toContain('recharge-price-card')
    expect(resultSource).toContain('recharge-price-card__ribbon')
    expect(resultSource).toContain('recharge-price-card__validity')
    expect(resultSource).toContain('rechargePricingCatalog')
    expect(resultSource).toContain('积分有效时间')
    expect(resultSource).toContain('item.validity')
    expect(resultSource).toContain('model-price-grid')
    expect(resultSource).toContain('model-price-card')
    expect(resultSource).toContain('gpt-image-2')
    expect(resultSource).not.toContain('{{ model.price }}')
    expect(resultSource).not.toContain('¥0.15~¥0.3 / 次')
    expect(resultSource).toContain('空状态占位')
    expect(resultSource).toContain('效果展示')
    expect(resultSource).toContain('任务进度')
    expect(resultSource).toContain('latestTask')
    expect(resultSource).toContain('latest-task-progress')
    expect(resultSource).toContain('当前组')
    expect(resultSource).toContain('组内进度')
    expect(resultSource).toContain('失败原因')
    expect(resultSource).toContain('latestTask?.error')
    expect(resultSource).toContain('panel-content--display-scroll')
    expect(resultSource).toContain('scrollbar-hidden')
    expect(resultSource).toContain('group-output-grid--scroll')
    expect(resultSource).toContain('四模型效果对比')
    expect(resultSource).toContain('单模型效果展示')
    expect(resultSource).toContain('comparison-grid comparison-grid--single comparison-grid--adaptive')
    expect(resultSource).toContain('comparison-card comparison-card--adaptive')
    expect(resultSource).toContain('批次输出')
    expect(resultSource).toContain('result-group-card__elapsed')
    expect(resultSource).toContain('发送提示词')
    expect(resultSource).toContain('promptFinal')
    expect(resultSource).toContain('rows="3"')
    expect(resultSource).toContain('下载图片')
    expect(resultSource).toContain('preview-modal')
    expect(resultSource).not.toContain('文本结果')
    expect(resultSource).not.toContain("showCopywriting")

    expect(exportSource).toContain('批量下载')
    expect(exportSource).not.toContain('批量选择性下载')
    expect(exportSource).toContain('复选框')
    expect(exportSource).toContain('itemCount')
    expect(exportSource).toContain('wenjianjia.png')
    expect(exportSource).toContain('down.png')
    expect(exportSource).toContain('shanchu.png')
    expect(exportSource).toContain('delete-export-item')
    expect(exportSource).toContain('handleDeleteExportItem')
    expect(exportSource).toContain('open-output-directory')
    expect(exportSource).toContain('export-item__toggle')
    expect(exportSource).toContain('export-item__actions')
    expect(exportSource).toContain('export-download-button')
    expect(exportSource).toContain('downloadCleanupEnabled')
    expect(exportSource).toContain('toggle-download-cleanup')
    expect(exportSource).toContain('自动删除')
    expect(exportSource).toContain('section-header__actions')
    expect(exportSource).not.toContain('下载后自动删除已导出的结果文件夹')
    expect(exportSource).toContain('scrollbar-hidden')
    expect(exportSource).toContain('const pageSize = 8')
    expect(exportSource).toContain('pagedExportItems')
    expect(exportSource).toContain('totalPages')
    expect(exportSource).toContain('export-pagination')
    expect(exportSource).toContain('pagination-arrow-button')
    expect(exportSource).toContain('pagination-arrow-button__triangle--left')
    expect(exportSource).toContain('pagination-arrow-button__triangle--right')
    expect(exportSource).toContain('aria-label="上一页"')
    expect(exportSource).toContain('aria-label="下一页"')
    expect(exportSource).toContain('个图片')
    expect(exportSource).not.toContain('个结果文件')

    const taskSidebarSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/TaskManagerSidebar.vue'), 'utf8')
    expect(taskSidebarSource).toContain('结束任务')
    expect(taskSidebarSource).toContain('stop-task')
    expect(taskSidebarSource).toContain('isStoppableTask')
    expect(taskSidebarSource).toContain('task.error')
    expect(taskSidebarSource).toContain('task-card__error')
    expect(taskSidebarSource).toContain('task-card__footer')
    expect(taskSidebarSource).toContain('downloadCleanupEnabled')
    expect(taskSidebarSource).toContain('toggle-download-cleanup')

    expect(dashboardSource).not.toContain('文案生成统计')
    expect(dashboardSource).toContain('单图测试统计')
    expect(dashboardSource).toContain('单图设计统计')
    expect(dashboardSource).toContain('套图设计统计')
    expect(dashboardSource).toContain('套图生成统计')
    expect(dashboardSource).toContain('服务配置状态')
    expect(dashboardSource).toContain('API 已由服务方预配置')
    expect(dashboardSource).toContain('如需更换配置，请联系服务方')
    expect(dashboardSource).toContain('用户主机信息')
    expect(dashboardSource).toContain('积分仪表盘')
    expect(dashboardSource).toContain('本地任务积分记录')
    expect(dashboardSource).toContain('本栏为本地模拟记账，真实数据以仪表盘为准')
    expect(dashboardSource).toContain('网络监控')
    expect(dashboardSource).toContain('networkMonitorCard')
    expect(dashboardSource).toContain('networkMonitorPoints')
    expect(dashboardSource).toContain('dashboard-network-monitor')
    expect(dashboardSource).toContain('dashboard-column--stats-stack')
    expect(dashboardSource).toContain('dashboard-column__stack')
    expect(dashboardSource).toContain('最近请求延迟')
    expect(dashboardSource).toContain('dashboard-network-monitor__polyline')
    expect(dashboardSource).toContain('dashboard-network-monitor__metric')
    expect(dashboardSource).not.toContain('最近 12 次请求')
    expect(dashboardSource).toContain('剩余积分')
    expect(dashboardSource).toContain('总积分')
    expect(dashboardSource).toContain('更新总积分')
    expect(dashboardSource).toContain('更新剩余积分')
    expect(dashboardSource).toContain('creditGaugeGlow')
    expect(dashboardSource).toContain('creditGaugeProgress')
    expect(dashboardSource).toContain('dashboard-credit-gauge')
    expect(dashboardSource).toContain('dashboard-credit-gauge__arc dashboard-credit-gauge__arc--active')
    expect(dashboardSource).toContain('dashboard-credit-gauge__value')
    expect(dashboardSource).toContain('{{ remainingCredits }} / {{ totalCredits }}')
    expect(dashboardSource).toContain('#38d9ff')
    expect(dashboardSource).toContain('#4ade80')
    expect(dashboardSource).toContain('#ff5f6d')
    expect(dashboardSource).not.toContain('creditNeedleRotation')
    expect(dashboardSource).not.toContain('creditGaugeMarkers')
    expect(dashboardSource).not.toContain('dashboard-credit-gauge__ticks')
    expect(dashboardSource).not.toContain('dashboard-credit-gauge__marker-labels')
    expect(dashboardSource).not.toContain('dashboard-credit-gauge__scale')
    expect(dashboardSource).not.toContain('dashboard-credit-gauge__needle')
    expect(dashboardSource).not.toContain('dashboard-credit-gauge__needle-cap')
    expect(dashboardSource).not.toContain('<span>0%</span>')
    expect(dashboardSource).not.toContain('<span>100%</span>')
    expect(dashboardSource).not.toContain("label: '25%'")
    expect(dashboardSource).not.toContain("label: '50%'")
    expect(dashboardSource).not.toContain("label: '75%'")
    expect(dashboardSource).not.toContain('当前档位')
    expect(dashboardSource).not.toContain('最近变动')
    expect(dashboardSource).toContain('冻结积分')
    expect(dashboardSource).toContain('已用积分')
    expect(dashboardSource).toContain('isRefreshingTotalCredits')
    expect(dashboardSource).toContain('isRefreshingRemainingCredits')
    expect(dashboardSource).toContain('dashboard-credit-adjust__grid')
    expect(dashboardSource).toContain('dashboard-credit-adjust__actions')
    expect(dashboardSource).toContain('dashboard-credit-adjust__action-group')
    expect(dashboardSource).toContain('refresh-total-credits')
    expect(dashboardSource).toContain('refresh-remaining-credits')
    expect(dashboardSource).toContain('secondary-action secondary-action--compact')
    expect(dashboardSource).toContain('creditMessagesCard')
    expect(dashboardSource).toContain('workspaceDashboard.creditMessages')
    expect(dashboardSource).toContain('dashboard-credit-message-list')
    expect(dashboardSource).toContain('refresh-total-credits')
    expect(dashboardSource).toContain('refresh-remaining-credits')
    expect(dashboardSource).toContain('模型调用次数')
    expect(dashboardSource).not.toContain('API-Key 1')
    expect(dashboardSource).not.toContain('API-Key 2')
    expect(dashboardSource).not.toContain('启用 Key 1')
    expect(dashboardSource).not.toContain('启用 Key 2')
    expect(dashboardSource).not.toContain('保存配置')
    expect(dashboardSource).not.toContain('接口节点')
    expect(dashboardSource).not.toContain('apiBaseUrl')
    expect(dashboardSource).not.toContain('国内节点')
    expect(dashboardSource).not.toContain('海外节点')

    expect(adminPasswordDialogSource).toContain('管理员验证')
    expect(adminPasswordDialogSource).toContain('请输入管理员密码')
    expect(adminPasswordDialogSource).toContain('确认')
    expect(adminPasswordDialogSource).toContain('取消')
    expect(adminPasswordDialogSource).not.toContain("@click.self=\"emit('close')\"")

    expect(adminApiKeyDialogSource).toContain('管理员 API-Key 配置')
    expect(adminApiKeyDialogSource).toContain('API-Key')
    expect(adminApiKeyDialogSource).toContain('保存')
    expect(adminApiKeyDialogSource).not.toContain("@click.self=\"emit('close')\"")

    const clearRuntimeDialogSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/ClearRuntimeConfirmDialog.vue'), 'utf8')
    expect(clearRuntimeDialogSource).toContain('一键清理确认')
    expect(clearRuntimeDialogSource).toContain('确认执行一键清理吗？')
    expect(clearRuntimeDialogSource).toContain("emit('confirm')")
    expect(clearRuntimeDialogSource).toContain("emit('close')")
    expect(styleSource).toContain('.clear-runtime-confirm-modal')
    expect(styleSource).toContain('.clear-runtime-confirm-modal__card')

    expect(promptLibrarySource).toContain('系统提示词')
    expect(promptLibrarySource).toContain('expandedPositiveTemplateId')
    expect(promptLibrarySource).toContain('allTemplateDrafts')
    expect(promptLibrarySource).toContain("source: template.source === 'system-fixed' ? 'system-fixed' : fallbackSource")
    expect(promptLibrarySource).toContain('删除正向模板')
    expect(promptLibrarySource).toContain('prompt-library-column__body scrollbar-hidden')
    expect(promptLibrarySource).toContain('保存正向模板')
    expect(promptLibrarySource).toContain('新增提示模板')
    expect(promptLibrarySource).toContain('系统模板')
    expect(promptLibrarySource).toContain('自定义模板')
    expect(promptLibrarySource).not.toContain('v-for="template in customPromptTemplates"')
    expect(promptLibrarySource).toContain('反向提示词库')
    expect(promptLibrarySource).toContain('expandedNegativeTemplateId')
    expect(promptLibrarySource).toContain('sortedNegativePromptTemplates')
    expect(promptLibrarySource).toContain('保存反向提示词模板')
    expect(promptLibrarySource).toContain('删除反向提示词模板')
    expect(promptLibrarySource).toContain('toggleNegativeTemplate')
    expect(promptLibrarySource).toContain('prompt-template-card')
    expect(promptLibrarySource).toContain('prompt-template-card__header')
    expect(promptLibrarySource).toContain('prompt-template-card__content')
    expect(promptLibrarySource).toContain('prompt-template-card__toggle')
    expect(promptLibrarySource).toContain('prompt-template-add-button')
    expect(promptLibrarySource).not.toContain('prompt-template-editor')
    expect(promptLibrarySource).toContain('FormTextControl')
    expect(promptLibrarySource).toContain('电商通用')
    expect(promptLibrarySource).toContain('电商模特')
    expect(promptLibrarySource).toContain('电商静物')
    expect(promptLibrarySource).toContain('提示词格式')
    expect(promptLibrarySource).toContain('推荐字符数')
    expect(promptLibrarySource).toContain('写法要点')
    expect(promptLibrarySource).toContain('头像、Q 版人物、表情包')
    expect(promptLibrarySource).toContain('60～150')
    expect(promptLibrarySource).toContain('主体 + 风格 + 简单背景，简洁干净')
    expect(promptLibrarySource).toContain('单人插画、古风 / 二次元人设')
    expect(promptLibrarySource).toContain('150～300')
    expect(promptLibrarySource).toContain('外貌 + 服饰 + 姿态 + 氛围 + 画风')
    expect(promptLibrarySource).toContain('产品图、静物、美食')
    expect(promptLibrarySource).toContain('产品细节 + 材质 + 光线 + 简约场景')
    expect(promptLibrarySource).toContain('风景、氛围感壁纸')
    expect(promptLibrarySource).toContain('200～400')
    expect(promptLibrarySource).toContain('环境 + 时间天气 + 光影 + 色调风格')
    expect(promptLibrarySource).toContain('多人剧情、赛博朋克 / 奇幻大场景')
    expect(promptLibrarySource).toContain('400～800')
    expect(promptLibrarySource).toContain('人物 + 动作 + 环境 + 镜头 + 整体氛围，语句连贯')
    expect(promptLibrarySource).toContain('prompt-format-card')
    expect(promptLibrarySource).not.toContain('标签库')
    expect(promptLibrarySource).not.toContain('增加分类')
    expect(promptLibrarySource).not.toContain('新建标签')
    expect(promptLibrarySource).not.toContain('删除标签')
    expect(promptLibrarySource).not.toContain('删除分类')
    expect(promptLibrarySource).not.toContain('半透明绿色')
    expect(promptLibrarySource).not.toContain('prompt-tag-category-card')
    expect(promptLibrarySource).not.toContain('prompt-tag-chip-list')
    expect(promptLibrarySource).not.toContain('prompt-tag-chip')
    expect(promptLibrarySource).toContain('禁用词提示')
    expect(promptLibrarySource).toContain('警告词提示')
    expect(promptLibrarySource).toContain('prompt-library-column--risk')
    expect(promptLibrarySource).toContain('以下词建议直接避免使用')
    expect(promptLibrarySource).toContain('以下词建议改写后再使用')
    expect(promptLibrarySource).not.toContain('这类词会显著提高保留原图或直接失败的概率。')
    expect(promptLibrarySource).not.toContain('建议替换为更明确的重绘描述，避免生成结果过于保守。')
    expect(promptLibrarySource).not.toContain('提示词存储')
    expect(promptLibrarySource).toContain('和原图一致')
    expect(promptLibrarySource).toContain('保留原图风格')
    expect(parameterSource).not.toContain('已选标签')
    expect(parameterSource).not.toContain('清空标签')
    expect(parameterSource).not.toContain('prompt-tag-builder__header')
    expect(parameterSource).not.toContain('toggleTagPicker')
    expect(parameterSource).not.toContain('selectedGlobalTagIds')
    expect(parameterSource).toContain('<span>图片类型</span>')
    expect(parameterSource).not.toContain('单张标签')
    expect(parameterSource).not.toContain('复制到后续')
    expect(parameterSource).not.toContain('assignment-card__tag-panel')
    expect(parameterSource).not.toContain('assignment-card__tag-chip')
    expect(parameterSource).not.toContain('applyAssignmentSettingsToFollowing')
    expect(parameterSource).not.toContain('toggleAssignmentTag')
    expect(parameterSource).toContain('createUploadDirectoryBinding')
    expect(parameterSource).toContain('createAssignmentPromptBinding')
    expect(parameterSource).toContain('createSeriesGeneratePromptBinding')
  })

  it('uses stable v-model bindings for editable parameter text fields', () => {
    const parameterSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/ParameterSettingsPanel.vue'), 'utf8')

    expect(parameterSource).toContain('const taskNameModel = createFieldBinding(\'taskName\')')
    expect(parameterSource).toContain('const seriesDesignGlobalPromptModel = createFieldBinding(\'globalPrompt\')')
    expect(parameterSource).toContain('const seriesGenerateGlobalPromptModel = createFieldBinding(\'globalPrompt\')')
    expect(parameterSource).toContain('v-model="taskNameModel"')
    expect(parameterSource).toContain('v-model="singleImagePromptModel"')
    expect(parameterSource).toContain('v-model="singleImageNotesModel"')
    expect(parameterSource).toContain('v-model="singleDesignPromptModel"')
    expect(parameterSource).toContain('v-model="singleDesignNotesModel"')
    expect(parameterSource).toContain('v-model="seriesDesignGlobalPromptModel"')
    expect(parameterSource).toContain('v-model="seriesGenerateGlobalPromptModel"')
    expect(parameterSource).not.toContain('@input="emitField(\'taskName\', $event.target.value)"')
    expect(parameterSource).not.toContain('@input="emitField(\'globalPrompt\', $event.target.value)"')
    expect(parameterSource).toContain('v-model="singleImageUploadDirectoryModel"')
    expect(parameterSource).toContain('v-model="singleDesignUploadDirectoryModel"')
    expect(parameterSource).toContain('v-model="seriesDesignUploadDirectoryModel"')
    expect(parameterSource).toContain('v-model="seriesGenerateUploadDirectoryModel"')
  })

  it('keeps FormTextControl fully controlled by parent model updates', () => {
    const formTextControlSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/FormTextControl.vue'), 'utf8')

    expect(formTextControlSource).toContain('const stringValue = computed(() => {')
    expect(formTextControlSource).toContain("emit('update:modelValue', event?.target?.value ?? '')")
    expect(formTextControlSource).toContain(':value="stringValue"')
    expect(formTextControlSource).not.toContain('const localValue = ref(')
    expect(formTextControlSource).not.toContain('watch(localValue')
  })

  it('defines floating agent launcher and a chat-first floating agent panel shell', () => {
    const floatingLauncherSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/FloatingAgentLauncher.vue'), 'utf8')
    const floatingPanelSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/FloatingAgentPanel.vue'), 'utf8')
    const scenePresetSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/config/agentScenePresets.js'), 'utf8')

    expect(floatingLauncherSource).toContain('AI智能体')
    expect(floatingLauncherSource).toContain('floating-agent-launcher')
    expect(floatingLauncherSource).toContain("emit('toggle')")

    expect(floatingPanelSource).toContain('floating-agent-panel')
    expect(floatingPanelSource).toContain('聊天记录')
    expect(floatingPanelSource).toContain('当前菜单')
    expect(floatingPanelSource).toContain('发送')
    expect(floatingPanelSource).toContain('确认填写')
    expect(floatingPanelSource).toContain('仅辅助填写当前页面参数')
    expect(floatingPanelSource).toContain("emit('close')")
    expect(floatingPanelSource).toContain("emit('send')")
    expect(floatingPanelSource).toContain("emit('confirm-fill')")
    expect(floatingPanelSource).toContain('conversationMessages')
    expect(floatingPanelSource).toContain('pendingQuestion')
    expect(floatingPanelSource).toContain('confirmCard')
    expect(floatingPanelSource).toContain('draftSuggestion')
    expect(floatingPanelSource).not.toContain('应用到当前任务')
    expect(floatingPanelSource).not.toContain('生成建议')
    expect(floatingPanelSource).toContain('activeMenu')
    expect(floatingPanelSource).toContain('scenePresets')
    expect(floatingPanelSource).toContain('floating-agent-panel__presets')
    expect(floatingPanelSource).toContain('floating-agent-panel__preset-grid')
    expect(floatingPanelSource).toContain('floating-agent-panel__preset-card')
    expect(floatingPanelSource).toContain('floating-agent-panel__preset-select')
    expect(floatingPanelSource).toContain('常用场景')
    expect(floatingPanelSource).toContain('更多场景')
    expect(floatingPanelSource).toContain('当前菜单暂无推荐场景')
    expect(floatingPanelSource).toContain("emit('select-scene-preset'")

    expect(scenePresetSource).toContain('agentScenePresets')
    expect(scenePresetSource).toContain('getAgentScenePresetsByMenu')
    expect(scenePresetSource).toContain("'single-design'")
    expect(scenePresetSource).toContain("'series-design'")
    expect(scenePresetSource).toContain("'series-generate'")
    expect(scenePresetSource).toContain('电商主图')
    expect(scenePresetSource).toContain('详情页套组')
    expect(scenePresetSource).toContain('多图统一风格重设计')
    expect(scenePresetSource).toContain('isFeatured')
    expect(scenePresetSource).toContain('sortOrder')
  })

  it('contains the restored agent settings shell with profile cards, enable action, and model catalog apply actions', () => {
    const designWorkspaceSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/DesignWorkspace.vue'), 'utf8')
    const agentSettingsSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/AgentSettingsPanel.vue'), 'utf8')

    expect(designWorkspaceSource).toContain('AgentSettingsPanel')
    expect(agentSettingsSource).toContain('Agent设置')
    expect(agentSettingsSource).toContain('参数设置')
    expect(agentSettingsSource).toContain('配置档案')
    expect(agentSettingsSource).toContain('启用')
    expect(agentSettingsSource).toContain('已启用')
    expect(agentSettingsSource).toContain('删除')
    expect(agentSettingsSource).toContain('保存配置')
    expect(agentSettingsSource).toContain('清空新建')
    expect(agentSettingsSource).toContain('可接入模型')
    expect(agentSettingsSource).toContain('应用')
    expect(agentSettingsSource).toContain('免费模型')
    expect(agentSettingsSource).toContain('付费模型')
    expect(agentSettingsSource).toContain('agent-settings-panel__profile-top')
    expect(agentSettingsSource).toContain('agent-settings-panel__profile-head')
    expect(agentSettingsSource).toContain('agent-settings-panel__profile-actions')
    expect(agentSettingsSource.indexOf('删除')).toBeLessThan(agentSettingsSource.indexOf('编辑'))
    expect(designWorkspaceSource).toContain('remove-agent-profile')
    expect(agentSettingsSource).not.toContain('记住到本地')
    expect(agentSettingsSource).not.toContain('API Host')
    expect(agentSettingsSource).not.toContain('Settings')
  })
})
