import { describe, expect, it } from 'vitest'
import fs from 'node:fs'
import path from 'node:path'

describe('styles source', () => {
  it('contains fixed shell, internal scroll areas and only the dark theme', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/assets/styles.css'), 'utf8')

    expect(source).toContain("[data-theme='dark']")
    expect(source).not.toContain("[data-theme='light']")
    expect(source).not.toContain("[data-theme='eye-care']")
    expect(source).toContain('.app-shell')
    expect(source).toContain('flex-direction: column;')
    expect(source).toContain('height: 100vh;')
    expect(source).toContain('.shell-grid')
    expect(source).toContain('flex: 1;')
    expect(source).toContain('grid-template-columns: minmax(0, 1fr) minmax(0, 6fr) minmax(0, 1fr);')
    expect(source).toContain('.shell-grid__sidebar')
    expect(source).toContain('.shell-grid__workspace')
    expect(source).toContain('.shell-grid__tasks')
    expect(source).toContain('.app-notice-layer')
    expect(source).toContain('.app-notice')
    expect(source).toContain('.app-notice--success')
    expect(source).toContain('.app-notice--error')
    expect(source).toContain('overflow: hidden;')
    expect(source).toContain('.module-scroll')
    expect(source).toContain('overflow: hidden;')
    expect(source).toContain('.topbar-contact-actions')
    expect(source).toContain('.topbar-right-actions')
    expect(source).toContain('.topbar-contact-button')
    expect(source).toContain('.contact-preview-modal')
    expect(source).toContain('.contact-preview-modal__image-grid')
    expect(source).toContain('.admin-password-modal')
    expect(source).toContain('.admin-api-key-modal')
    expect(source).toContain('z-index: 40;')
    expect(source).toContain('.scrollbar-hidden')
    expect(source).toContain('.scrollbar-hidden::-webkit-scrollbar')
    expect(source).toContain('.panel-content--scrollable')
    expect(source).toContain('overflow-y: auto;')
    expect(source).toContain('.app-notice-layer')
    expect(source).toContain('z-index: 60;')
    expect(source).toContain('.floating-agent-panel__presets')
    expect(source).toContain('.floating-agent-panel__preset-grid')
    expect(source).toContain('.floating-agent-panel__preset-card')
    expect(source).toContain('.floating-agent-panel__preset-select')
    expect(source).toContain('.shell-grid__tasks-stack')
    expect(source).toContain('.shell-grid__agent-slot')
    expect(source).toContain('.floating-agent-launcher--docked')
    expect(source).toContain('.floating-agent-launcher__bot')
    expect(source).toContain('aspect-ratio: 1 / 1;')
    expect(source).not.toContain('.floating-agent-launcher {\n  position: fixed;')
  })

  it('contains workspace focus layout, paged task sidebar and task state styles', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/assets/styles.css'), 'utf8')

    expect(source).toContain('.workspace-panels')
    expect(source).toContain('grid-template-columns: repeat(3, minmax(0, 1fr));')
    expect(source).toContain('.workspace-panels--single')
    expect(source).toContain('grid-template-columns: minmax(0, 1fr);')
    expect(source).toContain('.workspace-panels--focus-display')
    expect(source).toContain('minmax(280px, 1fr) minmax(0, 1.8fr);')
    expect(source).toContain('.workspace-panel')
    expect(source).toContain('.workspace-dashboard')
    expect(source).toContain('.dashboard-column')
    expect(source).toContain('.dashboard-stat-card')
    expect(source).toContain('.dashboard-config-card')
    expect(source).toContain('.dashboard-stat-list')
    expect(source).toContain('grid-template-columns: repeat(2, minmax(0, 1fr));')
    expect(source).toContain('.dashboard-column--split > *')
    expect(source).toContain('height: 100%;')
    expect(source).toContain('.dashboard-info-list')
    expect(source).toContain('.workspace-dashboard__inner')
    expect(source).toContain('padding: 14px;')
    expect(source).toContain('.dashboard-column--stats-grid')
    expect(source).toContain('.dashboard-stat-overview-grid')
    expect(source).toContain('.dashboard-column--stats-stack')
    expect(source).toContain('.dashboard-column__stack')
    expect(source).toContain('.dashboard-column--credit')
    expect(source).toContain('.dashboard-credit-gauge')
    expect(source).toContain('.dashboard-credit-gauge__dial')
    expect(source).toContain('.dashboard-credit-gauge__track')
    expect(source).toContain('.dashboard-credit-gauge__arc--active')
    expect(source).toContain('.dashboard-credit-gauge__value')
    expect(source).toContain('.dashboard-credit-gauge__progress-band')
    expect(source).toContain('filter: blur(3px);')
    expect(source).toContain('drop-shadow(0 0 6px rgba(183, 144, 255, 0.18))')
    expect(source).toContain('drop-shadow(0 0 10px rgba(183, 144, 255, 0.12))')
    expect(source).not.toContain('.dashboard-credit-gauge__needle')
    expect(source).not.toContain('.dashboard-credit-gauge__needle-cap')
    expect(source).not.toContain('.dashboard-credit-gauge__scale')
    expect(source).not.toContain('filter: blur(8px);')
    expect(source).not.toContain('.dashboard-credit-gauge__metrics')
    expect(source).toContain('.dashboard-credit-message-list')
    expect(source).toContain('.dashboard-credit-message-row')
    expect(source).toContain('.dashboard-credit-adjust__grid')
    expect(source).toContain('grid-template-columns: repeat(2, minmax(0, 1fr));')
    expect(source).toContain('.dashboard-credit-adjust__actions')
    expect(source).toContain('.dashboard-credit-adjust__action-group')
    expect(source).toContain('.credit-adjustment-apply')
    expect(source).toContain('.credit-total-save')
    expect(source).toContain('.secondary-action--compact')
    expect(source).toContain('min-height: 34px;')
    expect(source).toContain('padding: 0 10px;')
    expect(source).toContain('.task-status--waiting')
    expect(source).toContain('.task-status--running')
    expect(source).toContain('.task-status--completed')
    expect(source).toContain('.task-status--failed')
    expect(source).toContain('.task-progress__bar')
    expect(source).toContain('.task-list--paged')
    expect(source).toContain('.task-pagination')
    expect(source).toContain('.pagination-arrow-button')
    expect(source).toContain('.pagination-arrow-button__triangle')
    expect(source).toContain('.pagination-arrow-button__triangle--left')
    expect(source).toContain('.pagination-arrow-button__triangle--right')
    expect(source).toContain('.task-sidebar-empty')
    expect(source).toContain('.task-sidebar-shell--card')
    expect(source).toContain('@media (max-width: 1680px)')
    expect(source).toContain('@media (max-width: 1360px)')
    expect(source).toContain('min-width: 0;')
    expect(source).toContain('.model-price-grid')
    expect(source).toContain('grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));')
    expect(source).toContain('.recharge-price-grid')
    expect(source).toContain('grid-template-columns: repeat(3, minmax(0, 1fr));')
    expect(source).toContain('.recharge-price-card')
    expect(source).toContain('.section-title--centered')
    expect(source).toContain('text-align: center;')
    expect(source).toContain('.recharge-price-card__ribbon')
    expect(source).toContain('filter: brightness(0.72);')
    expect(source).toContain('font-size: 20px !important;')
    expect(source).toContain('transform: rotate(35deg);')
    expect(source).toContain('.prompt-library-grid')
    expect(source).toContain('.prompt-library-column')
    expect(source).toContain('.prompt-template-row')
    expect(source).toContain('.prompt-import-modal')
    expect(source).toContain('.select-icon-field')
    expect(source).toContain('.select-icon-field select')
    expect(source).toContain('color-scheme: dark;')
    expect(source).toContain('.select-icon-field select option')
    expect(source).toContain('background: var(--panel-strong);')
    expect(source).toContain('.model-price-card')
    expect(source).toContain('.panel-content--export-scroll')
    expect(source).toContain('.panel-content--display-scroll')
    expect(source).toContain('.export-download-button')
    expect(source).toContain('width: 100%;')
    expect(source).toContain('.export-item__actions')
    expect(source).toContain('justify-content: center;')
    expect(source).toContain('flex-direction: column;')
    expect(source).toContain('align-items: flex-end;')
    expect(source).toContain('.export-item__toggle')
    expect(source).toContain('grid-template-columns: auto minmax(0, 1fr) auto;')
    expect(source).toContain('.export-item__checkbox')
    expect(source).toContain('align-self: center;')
    expect(source).toContain('justify-self: center;')
    expect(source).toContain('margin: 0;')
    expect(source).toContain('.export-item__copy strong')
    expect(source).toContain('font-size: 13px;')
    expect(source).toContain('.export-item__copy small')
    expect(source).toContain('font-size: 11px;')
    expect(source).toContain('.comparison-grid')
    expect(source).toContain('grid-template-columns: repeat(auto-fit, minmax(190px, 1fr));')
    expect(source).toContain('.comparison-grid--adaptive')
    expect(source).toContain('.comparison-card--adaptive')
    expect(source).toContain('.comparison-card__preview')
    expect(source).toContain('.comparison-card__preview img')
    expect(source).toContain('.image-result-card__preview')
    expect(source).toContain('.image-result-card__preview img')
    expect(source).toContain('height: clamp(220px, 24vw, 320px);')
    expect(source).toContain('max-width: 100%;')
    expect(source).toContain('max-height: 100%;')
    expect(source).toContain('height: auto;')
    expect(source).toContain('object-fit: contain;')
    expect(source).toContain('.group-output-grid--scroll')
    expect(source).toContain('.result-group-card__elapsed')
    expect(source).toContain('grid-auto-flow: column;')
    expect(source).toContain('overflow-x: auto;')
    expect(source).toContain('.latest-task-progress')
    expect(source).toContain('.latest-task-progress__bar')
    expect(source).toContain('.dashboard-network-monitor')
    expect(source).toContain('.dashboard-network-monitor__chart')
    expect(source).toContain('.dashboard-network-monitor__polyline')
    expect(source).toContain('.dashboard-network-monitor__list')
    expect(source).toContain('.dashboard-network-monitor__row')
    expect(source).toContain('.dashboard-network-monitor__metric')
    expect(source).toContain('grid-template-rows: minmax(0, 2fr) auto minmax(0, 0.7fr);')
    expect(source).toContain('min-height: 216px;')
    expect(source).toContain('gap: clamp(10px, 1vw, 14px);')
    expect(source).toContain('.topbar-right-actions')
    expect(source).toContain('justify-self: end;')
    expect(source).toContain('position: static;')
    expect(source).toContain('.agent-settings-panel')
    expect(source).toContain('.agent-settings-panel__layout')
    expect(source).toContain('.agent-settings-panel__profiles')
    expect(source).toContain('.agent-settings-panel__profile-card')
    expect(source).toContain('.agent-settings-panel__profile-card--active')
    expect(source).toContain('.agent-settings-panel__profile-top')
    expect(source).toContain('.agent-settings-panel__profile-head')
    expect(source).toContain('.agent-settings-panel__form {')
    expect(source).toContain('.agent-settings-panel__catalog')
    expect(source).toContain('.agent-settings-panel__model-card')
  })
})
